"""Add card_activities table for tracking card history

Revision ID: 7b1d6dc18ec4
Revises: 035c1508fe6f
Create Date: 2025-11-03 12:57:53.948138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b1d6dc18ec4'
down_revision = '035c1508fe6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('activity_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_activities_card_id'), 'card_activities', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_activities_id'), 'card_activities', ['id'], unique=False)
    op.create_index(op.f('ix_card_activities_user_id'), 'card_activities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_activities_user_id'), table_name='card_activities')
    op.drop_index(op.f('ix_card_activities_id'), table_name='card_activities')
    op.drop_index(op.f('ix_card_activities_card_id'), table_name='card_activities')
    op.drop_table('card_activities')
    # ### end Alembic commands ###
