"""Add workspace_labels and card_labels tables

Revision ID: 9f081ea649fe
Revises: 7b1d6dc18ec4
Create Date: 2025-11-03 14:50:49.660950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f081ea649fe'
down_revision = '7b1d6dc18ec4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_labels_id'), 'workspace_labels', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_labels_workspace_id'), 'workspace_labels', ['workspace_id'], unique=False)
    op.create_table('card_labels',
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('label_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_id'], ['workspace_labels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id', 'label_id')
    )
    op.create_index(op.f('ix_card_labels_card_id'), 'card_labels', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_labels_label_id'), 'card_labels', ['label_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_labels_label_id'), table_name='card_labels')
    op.drop_index(op.f('ix_card_labels_card_id'), table_name='card_labels')
    op.drop_table('card_labels')
    op.drop_index(op.f('ix_workspace_labels_workspace_id'), table_name='workspace_labels')
    op.drop_index(op.f('ix_workspace_labels_id'), table_name='workspace_labels')
    op.drop_table('workspace_labels')
    # ### end Alembic commands ###
